### PR TITLE
remove ias related

### PR DESCRIPTION
**Pull request by ChenKim**
JIRA: None
Test: Test on Joule.
Remove ias related to solve compile issue for generating incremental ota package.

Signed-off-by: xihua.chen <xihua.chen@intel.com>

### CODE REVIEW

**Comment by kalyankondapally** [comment]
can u update commit message to reflect what this is expected to solve and add appropriate tests for someone to check

**Comment by ChenKim** [comment]
Hi @kalyankondapally ,
Commit message updated.

**Comment by kalyankondapally** [comment]
@sgnanase @Kishore409 You want to check this.

**Comment by sgnanase** [comment]
Merged ...

**Pull request closed without merging**
